print ("type value for a")
a = input()
print ("type value for b")
b = input()
print ("say something to this world")
c = input()
print ("the value of a is {}". format(a))
print ("the value of b is {}". format(b))
print ("the program says {}". format (c))
